<<<<<<< Updated upstream
=======
# Datasource MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=ecommerce_user
quarkus.datasource.password=ecommerce_password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/ecommerce_db

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.log.sql=true

# Parámetros básicos del servidor
quarkus.http.host=0.0.0.0
quarkus.http.port=8081
quarkus.http.idle-timeout=30S

# Access log HTTP 
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %Dms

# Observabilidad: Health checks
quarkus.smallrye-health.enabled=true
quarkus.smallrye-health.root-path=/q/health

# Observabilidad: Métricas Prometheus
quarkus.micrometer.enabled=true
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

#logs
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c] %s%e
quarkus.log.category."com.tuecommerce".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=DEBUG
>>>>>>> Stashed changes
